# Generated by Django 3.1 on 2020-10-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainDiscussion',
            fields=[
                ('dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_title', models.CharField(blank=True, max_length=45, null=True)),
                ('dis_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('dis_solved', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'main_discussion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainIp',
            fields=[
                ('ip_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=45, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'main_ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainWiki',
            fields=[
                ('wiki_id', models.AutoField(primary_key=True, serialize=False)),
                ('wiki_img', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('wiki_desc', models.TextField(blank=True, null=True)),
                ('wiki_title', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'main_wiki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_textfield', models.TextField()),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.mainip')),
                ('discussion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.maindiscussion')),
            ],
        ),
    ]
