# Generated by Django 3.1 on 2020-09-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hash_tag',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='rel_wiki_hashtag',
            old_name='hash_tag',
            new_name='hashtag',
        ),
    ]
